# This file was generated by GoReleaser. DO NOT EDIT.
cask "skyhook" do
  name "skyhook"
  desc "CLI for Skyhook."
  homepage "https://www.skyhook.io"
  version "2.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skyhook"

  on_macos do
    url "https://github.com/skyhook-io/skyhook-cli/releases/download/#{version}/skyhook_darwin_all.tar.gz"
    sha256 "f8dfd03a9f6f15ee5d435912be85286a31141df57897c3e1ff561b135e274211"
  end

  on_linux do
    on_intel do
      url "https://github.com/skyhook-io/skyhook-cli/releases/download/#{version}/skyhook_linux_amd64.tar.gz"
      sha256 "3d528df15e81e0e96a42ad5fe01dce8c6fe27e83a21e497d852849429e5d2060"
    end
    on_arm do
      url "https://github.com/skyhook-io/skyhook-cli/releases/download/#{version}/skyhook_linux_arm64.tar.gz"
      sha256 "e341577c579bb88b8a9334103ad7252cc00c262a0d9babf7f77bffa64429db1e"
    end
  end

  # No zap stanza required
end
