# This file was generated by GoReleaser. DO NOT EDIT.
cask "skyhook" do
  name "skyhook"
  desc "CLI for Skyhook."
  homepage "https://www.skyhook.io"
  version "2.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skyhook"

  on_macos do
    url "https://github.com/skyhook-io/skyhook-cli/releases/download/#{version}/skyhook_darwin_all.tar.gz"
    sha256 "20d878e69fa354b71d34accf8ae9253da8b7756b0ce65f59752ee3fd4ae27e71"
  end

  on_linux do
    on_intel do
      url "https://github.com/skyhook-io/skyhook-cli/releases/download/#{version}/skyhook_linux_amd64.tar.gz"
      sha256 "5605afef8b58b6c5b123c981f78d01f18910d7b92b7e797583d63fad93d6c45e"
    end
    on_arm do
      url "https://github.com/skyhook-io/skyhook-cli/releases/download/#{version}/skyhook_linux_arm64.tar.gz"
      sha256 "882fa94ab2a78f17a79407abce87817bc9fdd1b5524aaf88d9620bd0cbfc3f1b"
    end
  end

  # No zap stanza required
end
