# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skyhook < Formula
  desc "CLI for Skyhook."
  homepage "https://www.skyhook.io"
  version "2.3.2"

  on_macos do
    url "https://github.com/skyhook-io/skyhook-cli/releases/download/2.3.2/skyhook_darwin_all.tar.gz"
    sha256 "053f75a6367bc2869c598be712628587785107fa29c3704803267621590816c1"

    define_method(:install) do
      bin.install "skyhook"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/skyhook-cli/releases/download/2.3.2/skyhook_linux_amd64.tar.gz"
      sha256 "fc129e825994c210acf500b7aa69b9afff1fa0b1ee7fa495995daf1e595605c9"
      define_method(:install) do
        bin.install "skyhook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/skyhook-cli/releases/download/2.3.2/skyhook_linux_arm64.tar.gz"
      sha256 "28dcaaf256ad97e0bc8129c14a5002bc6995f84c051dd8f330aa6697cc01be8f"
      define_method(:install) do
        bin.install "skyhook"
      end
    end
  end
end
