# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkyhookExplorer < Formula
  desc "Kubernetes cluster visualization and topology explorer"
  homepage "https://github.com/skyhook-io/explorer"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyhook-io/explorer/releases/download/v0.3.0/explorer_0.3.0_darwin_amd64.tar.gz"
      sha256 "dc98d34d71ebdd4d2b6420ca890b057f218100baabd133280b1e9e8c62f8fdd7"

      def install
        bin.install "kubectl-explorer"
        bin.install_symlink "kubectl-explorer" => "skyhook-explorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyhook-io/explorer/releases/download/v0.3.0/explorer_0.3.0_darwin_arm64.tar.gz"
      sha256 "7eb5a87a35c71ed4188fb64b4a7504a642e1a720e0f6ab73fce3a0e4d11c8990"

      def install
        bin.install "kubectl-explorer"
        bin.install_symlink "kubectl-explorer" => "skyhook-explorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/explorer/releases/download/v0.3.0/explorer_0.3.0_linux_amd64.tar.gz"
      sha256 "e436174af2a7dbbfd6fbdd5854624ffa0a63b898a917f16cee529bb446e06779"
      def install
        bin.install "kubectl-explorer"
        bin.install_symlink "kubectl-explorer" => "skyhook-explorer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/explorer/releases/download/v0.3.0/explorer_0.3.0_linux_arm64.tar.gz"
      sha256 "abd2602ca25eb4d2eea7d44996b4161bbe54a19d17b40720faa25baa6a1b7535"
      def install
        bin.install "kubectl-explorer"
        bin.install_symlink "kubectl-explorer" => "skyhook-explorer"
      end
    end
  end

  test do
    system "#{bin}/kubectl-explorer", "--version"
  end
end
