# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkyhookExplorer < Formula
  desc "Kubernetes cluster visualization and topology explorer"
  homepage "https://github.com/skyhook-io/explorer"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyhook-io/explorer/releases/download/v0.1.1/explorer_0.1.1_darwin_amd64.tar.gz"
      sha256 "b940fa5522782883e21fbe89e0e79fdd9f3f6d02b2d9f04cd203d60e89b5eb74"

      def install
        bin.install "kubectl-explore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyhook-io/explorer/releases/download/v0.1.1/explorer_0.1.1_darwin_arm64.tar.gz"
      sha256 "b25e8727a42b72eec28aa79393f1df5fccafdcb8a919db5125fc2675b1f1536d"

      def install
        bin.install "kubectl-explore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/explorer/releases/download/v0.1.1/explorer_0.1.1_linux_amd64.tar.gz"
      sha256 "bb0b2a3c01978138ada50ac574900bfc274356221c33bbe08ab28017b6d6a0f6"
      def install
        bin.install "kubectl-explore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/explorer/releases/download/v0.1.1/explorer_0.1.1_linux_arm64.tar.gz"
      sha256 "796c9fae8f0c9739ec64aeb87f861ccdb7e07072b31b0cf14ccb09760b2e586d"
      def install
        bin.install "kubectl-explore"
      end
    end
  end

  test do
    system "#{bin}/kubectl-explore", "--version"
  end
end
